<?php
namespace Tools;
/** Class that contains the normalize method */
class Normalize {
    /** Call the provided getters in the provided object and generate an associative array of [getter => value]
     * 
     * @param Object $object Must be the one associated with the provided metadata
     * @param array $metadata Must be the associative array generated by the Metadata Object, related with the given object
     * 
     * @return array $normalizedArray Associative array with the getters as key and the properties values as values
     */
    public function normalizer($object, array $metadata) {
        $normalizedArray = [];

        foreach($metadata as $key => $value) {
            $getterToBeCalled = $key;
            $normalizedArray[$key] = $getterToBeCalled();
        }

        return $normalizedArray;
    }

}